### ISSUE TITLE
lesson2-focus/02-dom-order does not work on firefox and firefox Dev edition

### ISSUE THREAD

**Issue by Obayanju** [udacity/ud891#40]
Hi, thanks for his awesome course. I ran the solution for the lesson specified in the title on both browsers mentioned, but tabbing does not tab through the links. What is the reason for this? It seems weird that focus accessibility does not work on Firefox.

**Comment by Eduardo06sp** [comment]
Running on Linux, Firefox v62.0b9

Works perfectly fine, maybe try clicking on the site title where the browser tabs are to regain focus to the top?

Very strange, does it work on other websites?

**Comment by Obayanju** [comment]
Thank you. I tried that, but tabbing jumps straight to the footer's text box. I am running Firefox Quantum 61.0.1 (64-bit)

**Comment by robdodson** [comment]
I can't recall, I think we may have mentioned this in the course, but this is a Mac OS setting. You have to go to System Preferences > Keyboard and enable the setting that lets tab move focus to all controls (not just text fields). Otherwise Firefox and Safari will ignore links.

![image](https://user-images.githubusercontent.com/1066253/43670833-a37a5a2a-9745-11e8-9e2a-aa4a42b2bea9.png)
