### ISSUE TITLE
Lesson 3.6

### ISSUE THREAD

**Issue by emily-kay** [udacity/ud891#55]
The screen reader only says NaN NaN when it gets to the date fields. If you click to a different tab and click back to the flight booking tab, it says departure date first, letting you know which field it's on. The header flashes in the screen reader when tabbing over to it so it appears that it's a priority issue. 

The numbers also are only announced when you reach the year. Otherwise it continues to announce NaN NaN.

**Comment by emily-kay** [comment]
It seems like maybe the code that's being used is duplicated from 3.16 which may explain why the labels are missing.

**Comment by robdodson** [comment]
Yeah I think both of these are issues with the way Chrome is conveying those elements to chromevox-lite. I think over the years since we made this course, Chrome has changed its accessibility tree representation for those elements and now chromevox-lite is buggy. I'm not sure if it's something we can fix because the code for chromevox-lite is a bit of a black box 😅
